//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emps
    {
        public string empId { get; set; }
        public string name { get; set; }
        public string skills { get; set; }
        public string dept { get; set; }
    }
}
